//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proto.Data.Query
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTenants
    {
        public int TenantId { get; set; }
        public string AccountNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> Active { get; set; }
        public string PrimaryContactFirstName { get; set; }
        public string PrimaryContactLastName { get; set; }
        public string PrimaryContactPhone { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string OfficePhone { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public System.Guid RowGuid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ContactTypeId { get; set; }
    }
}
